version: '3.9'

services:
  web: 
    build: 
      context: /goodtrip
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    container_name: "goodtrip"
    environment:
      - ASPNETCORE_URLS=https://+443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Goodtrip123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/goodtrip.pfx
    volumes:
      - ./goodtrip/conf.d/https/:/https:ro
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Goodtrip123!"
      ACCEPT_EULA: "Y"
    container_name: goodtrip_db